name: Publish to Pypi
on:
  push:
    branches:
    - main

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build dist
        run: cd python && python setup.py sdist
 
