name: Publish to Pypi
on:
  push:
    branches:
    - main

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Build dist
        run: cd python && python -m pep517.build .
      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: python/dist/
          password: ${{ secrets.AZURE_HELPERS_PYPI_TOKEN }} 
